import { Link } from "react-router-dom";

const UPDATED = "17 September 2026";

function Section({ title, children }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-bold text-ink">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-ink/80">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <div className="animate-fade-in max-w-2xl space-y-6">
      <header>
        <h1 className="text-3xl font-bold text-ink">Terms &amp; Conditions</h1>
        <p className="mt-1 text-sm text-ink/60">Last updated {UPDATED}</p>
      </header>

      <div className="hoop-card-outline space-y-5 p-6">
        <Section title="What this is">
          <p>
            HoopIQ is a free basketball analytics project. It is offered as-is, for interest and
            entertainment, with no guarantee that it will be available, accurate or working at
            any given moment.
          </p>
        </Section>

        <Section title="Not affiliated with the NBA">
          <p>
            HoopIQ is an independent project with no affiliation to, endorsement by, or
            sponsorship from the National Basketball Association or any team. All team names,
            logos and marks belong to their owners. Statistics come from publicly available
            NBA.com endpoints and from Basketball-Reference-derived data, and are used here for
            analysis and commentary.
          </p>
        </Section>

        <Section title="The numbers can be wrong">
          <p>
            Statistics are pulled from third-party sources and may be delayed, incomplete or
            incorrect. Some seasons are not fully covered — the league's own stats API returns
            nothing before 1996-97, and those gaps are filled from other public data.
          </p>
          <p>
            Anything labelled a simulation, projection or comparison is a <strong className="text-ink">model,
            not a prediction</strong>. The rule simulator re-prices shots that were already taken;
            it does not know how players would adapt. Draft and trade tools are estimates built on
            assumptions that are stated on those pages.
          </p>
        </Section>

        <Section title="AI-generated content">
          <p>
            Scouting reports and the GM assistant are generated by a language model. They can be
            confidently wrong, and they are not scouting advice, investment advice, or a
            substitute for judgement. Check anything that matters against the underlying numbers.
          </p>
        </Section>

        <Section title="Do not bet on this">
          <p>
            Nothing here is betting advice and none of it is built or tested for wagering. Using
            these numbers to gamble is done entirely at your own risk.
          </p>
        </Section>

        <Section title="Fair use of the site">
          <p>
            Please do not attempt to overload the servers, bypass the rate limits, or use the
            multiplayer Arena to harass other players or to enter abusive display names. The
            service may be changed or withdrawn at any time.
          </p>
        </Section>

        <Section title="Liability">
          <p>
            To the fullest extent the law allows, this project and its author are not liable for
            any loss arising from use of the site or reliance on anything it produces.
          </p>
        </Section>

        <p className="border-t border-ink/15 pt-4 text-xs text-ink/60">
          These terms are a plain-language statement of intent for a hobby project, not legal
          advice, and have not been reviewed by a lawyer. If HoopIQ ever takes payments or
          operates commercially, have a professional review them.
        </p>
      </div>

      <p className="text-sm text-ink/70">
        See also the <Link to="/privacy" className="font-semibold text-terracotta hover:underline">Privacy Policy</Link>.
      </p>
    </div>
  );
}
